"""Added notes and users table

Revision ID: 07bd6eb2c9eb
Revises: 496aefde6380
Create Date: 2020-09-05 10:02:01.175213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bd6eb2c9eb'
down_revision = '496aefde6380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
