"""Added users table again

Revision ID: 0b53d82fb93f
Revises: 8be1a91a9feb
Create Date: 2020-09-05 00:40:14.568928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b53d82fb93f'
down_revision = '8be1a91a9feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
