"""Added password to users

Revision ID: 169271a724af
Revises: c7b03b062c7a
Create Date: 2020-08-29 22:27:50.304759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169271a724af'
down_revision = 'c7b03b062c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
