"""Update notes table column: ownerid

Revision ID: 1716f0aea839
Revises: b9571ba1fde6
Create Date: 2020-09-05 21:04:46.646579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1716f0aea839'
down_revision = 'b9571ba1fde6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner', sa.String(), nullable=True))
    # op.drop_column('notes', 'ownerid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('notes', sa.Column('ownerid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'owner')
    # ### end Alembic commands ###
