"""Added notes table

Revision ID: 1ae6ed11ce0d
Revises: 654dd1a6db52
Create Date: 2020-09-03 16:05:24.718914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae6ed11ce0d'
down_revision = '654dd1a6db52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
