"""The end

Revision ID: 2327f9633332
Revises: dbdfd1e5356c
Create Date: 2020-09-05 01:08:55.446693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2327f9633332'
down_revision = 'dbdfd1e5356c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
