"""Added notes table

Revision ID: 2dab75d7140b
Revises: 5443b51a704a
Create Date: 2020-09-05 00:22:00.168834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dab75d7140b'
down_revision = '5443b51a704a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_column('notes', 'ownerid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('ownerid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='demo_pkey')
    )
    # ### end Alembic commands ###
