"""Added users and notes tables

Revision ID: 32e4de67fa1f
Revises: 0505286e86e7
Create Date: 2020-08-24 13:13:40.351338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e4de67fa1f'
down_revision = '0505286e86e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('authorId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'authorId')
    # ### end Alembic commands ###
