"""Admin table

Revision ID: 34ef1bf3ce8d
Revises: adf12414a1d1
Create Date: 2020-09-07 01:27:59.481279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ef1bf3ce8d'
down_revision = 'adf12414a1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
