"""Added notes table

Revision ID: 3515e4614b23
Revises: 8c40b8e30ddd
Create Date: 2020-08-29 16:08:25.390132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3515e4614b23'
down_revision = '8c40b8e30ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
