"""Added notes table

Revision ID: 36999d9ab4fa
Revises: 92a05968b3bb
Create Date: 2020-09-09 16:39:05.118721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36999d9ab4fa'
down_revision = '92a05968b3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
