"""Added notes table

Revision ID: 3f2cff274c48
Revises: d3b1080c9e40
Create Date: 2020-09-03 16:22:10.431632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2cff274c48'
down_revision = 'd3b1080c9e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
