"""Added notes table

Revision ID: 496aefde6380
Revises: 2327f9633332
Create Date: 2020-09-05 01:11:19.167582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496aefde6380'
down_revision = '2327f9633332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
