"""Users table

Revision ID: 4ed36eca098d
Revises: 92f4f18e37cf
Create Date: 2020-09-05 00:47:24.904877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed36eca098d'
down_revision = '92f4f18e37cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
