"""Added notes table

Revision ID: 52da18b2462c
Revises: 
Create Date: 2020-07-21 12:00:18.388835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52da18b2462c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
