"""Added user table and modify notes table

Revision ID: 541dbeca952e
Revises: 0514e3418c6b
Create Date: 2020-09-05 03:13:36.277354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541dbeca952e'
down_revision = '0514e3418c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('notes', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'user')
    op.drop_table('users')
    # ### end Alembic commands ###
