"""Added notes table

Revision ID: 654dd1a6db52
Revises: a86ee1df99fd
Create Date: 2020-09-03 16:00:34.149013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654dd1a6db52'
down_revision = 'a86ee1df99fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
