"""updated password length

Revision ID: 674d46e33292
Revises: 367c1a811719
Create Date: 2020-09-08 17:35:11.839792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674d46e33292'
down_revision = '367c1a811719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
