"""increased password length

Revision ID: 83aa1e0bd5e1
Revises: 6b0cc6215d04
Create Date: 2020-09-08 17:55:40.260884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83aa1e0bd5e1'
down_revision = '6b0cc6215d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
