"""Added admin table

Revision ID: 879dcaef3beb
Revises: 1716f0aea839
Create Date: 2020-09-07 01:11:56.305033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879dcaef3beb'
down_revision = '1716f0aea839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
