"""Added users table

Revision ID: 8be1a91a9feb
Revises: b9571ba1fde6
Create Date: 2020-09-05 00:36:39.232137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be1a91a9feb'
down_revision = 'b9571ba1fde6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('ownerid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'ownerid')
    # ### end Alembic commands ###
