"""Added notes table

Revision ID: 8c40b8e30ddd
Revises: 5ad8b3dd18f0
Create Date: 2020-08-29 16:00:39.450312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c40b8e30ddd'
down_revision = '5ad8b3dd18f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
