"""Added notes table

Revision ID: 92a05968b3bb
Revises: b11510d8d1c6
Create Date: 2020-09-09 15:36:21.397636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92a05968b3bb'
down_revision = 'b11510d8d1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Note')
    op.drop_index('User.email_unique', table_name='User')
    op.drop_index('User.username_unique', table_name='User')
    op.drop_table('User')
    op.drop_table('_Migration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_Migration',
    sa.Column('revision', sa.INTEGER(), server_default=sa.text('nextval(\'"_Migration_revision_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('datamodel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('applied', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rolled_back', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datamodel_steps', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('database_migration', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('errors', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('revision', name='_Migration_pkey')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    op.create_index('User.username_unique', 'User', ['username'], unique=True)
    op.create_index('User.email_unique', 'User', ['email'], unique=True)
    op.create_table('Note',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Note_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Note_pkey')
    )
    # ### end Alembic commands ###
