"""Added users table once more

Revision ID: 92f4f18e37cf
Revises: 0b53d82fb93f
Create Date: 2020-09-05 00:44:23.420465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f4f18e37cf'
down_revision = '0b53d82fb93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
