"""Added users table

Revision ID: 99a73a32a088
Revises: 3515e4614b23
Create Date: 2020-08-29 20:01:53.732310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a73a32a088'
down_revision = '3515e4614b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
