"""Added created_at and updated_at column in note table

Revision ID: a2cb42a980e4
Revises: 3d2e2ffa3ad9
Create Date: 2020-09-11 10:44:28.366211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cb42a980e4'
down_revision = '3d2e2ffa3ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('note', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'updated_at')
    op.drop_column('note', 'created_at')
    # ### end Alembic commands ###
