"""Added notes table

Revision ID: b11510d8d1c6
Revises: 3f2cff274c48
Create Date: 2020-09-03 17:18:09.662844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11510d8d1c6'
down_revision = '3f2cff274c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
