"""Added notes table

Revision ID: d3b1080c9e40
Revises: 1ae6ed11ce0d
Create Date: 2020-09-03 16:15:44.113574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b1080c9e40'
down_revision = '1ae6ed11ce0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
